spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yangkun?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

mybatis:
  mapper-locations[0]: classpath:mybatis/auto/*Mapper.xml
  mapper-locations[1]: classpath:mybatis/*ExtMapper.xml